# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AnalysisService.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='AnalysisService.proto',
  package='com.github.agitolyev',
  syntax='proto3',
  serialized_options=b'P\001',
  serialized_pb=b'\n\x15\x41nalysisService.proto\x12\x14\x63om.github.agitolyev\"$\n\x14\x41nonymizationRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\"\n\x12\x41nonymizationReply\x12\x0c\n\x04text\x18\x02 \x01(\t\"\x1f\n\x0f\x41nalysisRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"D\n\rAnalysisReply\x12\x33\n\x06tokens\x18\x01 \x03(\x0b\x32#.com.github.agitolyev.AnalysisToken\"\xe7\x01\n\rAnalysisToken\x12\x38\n\x05\x66ield\x18\x01 \x01(\x0b\x32).com.github.agitolyev.AnalysisToken.Field\x12\r\n\x05score\x18\x02 \x01(\x01\x12>\n\x08location\x18\x03 \x01(\x0b\x32,.com.github.agitolyev.AnalysisToken.Location\x1a\x15\n\x05\x46ield\x12\x0c\n\x04name\x18\x01 \x01(\t\x1a\x36\n\x08Location\x12\r\n\x05start\x18\x01 \x01(\r\x12\x0b\n\x03\x65nd\x18\x02 \x01(\r\x12\x0e\n\x06length\x18\x03 \x01(\r2\xcf\x01\n\x0f\x41nalysisService\x12W\n\x07\x41nalyze\x12%.com.github.agitolyev.AnalysisRequest\x1a#.com.github.agitolyev.AnalysisReply\"\x00\x12\x63\n\tAnonymize\x12*.com.github.agitolyev.AnonymizationRequest\x1a(.com.github.agitolyev.AnonymizationReply\"\x00\x42\x02P\x01\x62\x06proto3'
)




_ANONYMIZATIONREQUEST = _descriptor.Descriptor(
  name='AnonymizationRequest',
  full_name='com.github.agitolyev.AnonymizationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='com.github.agitolyev.AnonymizationRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=83,
)


_ANONYMIZATIONREPLY = _descriptor.Descriptor(
  name='AnonymizationReply',
  full_name='com.github.agitolyev.AnonymizationReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='com.github.agitolyev.AnonymizationReply.text', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=119,
)


_ANALYSISREQUEST = _descriptor.Descriptor(
  name='AnalysisRequest',
  full_name='com.github.agitolyev.AnalysisRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='com.github.agitolyev.AnalysisRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=152,
)


_ANALYSISREPLY = _descriptor.Descriptor(
  name='AnalysisReply',
  full_name='com.github.agitolyev.AnalysisReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tokens', full_name='com.github.agitolyev.AnalysisReply.tokens', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=222,
)


_ANALYSISTOKEN_FIELD = _descriptor.Descriptor(
  name='Field',
  full_name='com.github.agitolyev.AnalysisToken.Field',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='com.github.agitolyev.AnalysisToken.Field.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=379,
  serialized_end=400,
)

_ANALYSISTOKEN_LOCATION = _descriptor.Descriptor(
  name='Location',
  full_name='com.github.agitolyev.AnalysisToken.Location',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='com.github.agitolyev.AnalysisToken.Location.start', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='com.github.agitolyev.AnalysisToken.Location.end', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='length', full_name='com.github.agitolyev.AnalysisToken.Location.length', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=402,
  serialized_end=456,
)

_ANALYSISTOKEN = _descriptor.Descriptor(
  name='AnalysisToken',
  full_name='com.github.agitolyev.AnalysisToken',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='field', full_name='com.github.agitolyev.AnalysisToken.field', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='com.github.agitolyev.AnalysisToken.score', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='com.github.agitolyev.AnalysisToken.location', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ANALYSISTOKEN_FIELD, _ANALYSISTOKEN_LOCATION, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=456,
)

_ANALYSISREPLY.fields_by_name['tokens'].message_type = _ANALYSISTOKEN
_ANALYSISTOKEN_FIELD.containing_type = _ANALYSISTOKEN
_ANALYSISTOKEN_LOCATION.containing_type = _ANALYSISTOKEN
_ANALYSISTOKEN.fields_by_name['field'].message_type = _ANALYSISTOKEN_FIELD
_ANALYSISTOKEN.fields_by_name['location'].message_type = _ANALYSISTOKEN_LOCATION
DESCRIPTOR.message_types_by_name['AnonymizationRequest'] = _ANONYMIZATIONREQUEST
DESCRIPTOR.message_types_by_name['AnonymizationReply'] = _ANONYMIZATIONREPLY
DESCRIPTOR.message_types_by_name['AnalysisRequest'] = _ANALYSISREQUEST
DESCRIPTOR.message_types_by_name['AnalysisReply'] = _ANALYSISREPLY
DESCRIPTOR.message_types_by_name['AnalysisToken'] = _ANALYSISTOKEN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AnonymizationRequest = _reflection.GeneratedProtocolMessageType('AnonymizationRequest', (_message.Message,), {
  'DESCRIPTOR' : _ANONYMIZATIONREQUEST,
  '__module__' : 'AnalysisService_pb2'
  # @@protoc_insertion_point(class_scope:com.github.agitolyev.AnonymizationRequest)
  })
_sym_db.RegisterMessage(AnonymizationRequest)

AnonymizationReply = _reflection.GeneratedProtocolMessageType('AnonymizationReply', (_message.Message,), {
  'DESCRIPTOR' : _ANONYMIZATIONREPLY,
  '__module__' : 'AnalysisService_pb2'
  # @@protoc_insertion_point(class_scope:com.github.agitolyev.AnonymizationReply)
  })
_sym_db.RegisterMessage(AnonymizationReply)

AnalysisRequest = _reflection.GeneratedProtocolMessageType('AnalysisRequest', (_message.Message,), {
  'DESCRIPTOR' : _ANALYSISREQUEST,
  '__module__' : 'AnalysisService_pb2'
  # @@protoc_insertion_point(class_scope:com.github.agitolyev.AnalysisRequest)
  })
_sym_db.RegisterMessage(AnalysisRequest)

AnalysisReply = _reflection.GeneratedProtocolMessageType('AnalysisReply', (_message.Message,), {
  'DESCRIPTOR' : _ANALYSISREPLY,
  '__module__' : 'AnalysisService_pb2'
  # @@protoc_insertion_point(class_scope:com.github.agitolyev.AnalysisReply)
  })
_sym_db.RegisterMessage(AnalysisReply)

AnalysisToken = _reflection.GeneratedProtocolMessageType('AnalysisToken', (_message.Message,), {

  'Field' : _reflection.GeneratedProtocolMessageType('Field', (_message.Message,), {
    'DESCRIPTOR' : _ANALYSISTOKEN_FIELD,
    '__module__' : 'AnalysisService_pb2'
    # @@protoc_insertion_point(class_scope:com.github.agitolyev.AnalysisToken.Field)
    })
  ,

  'Location' : _reflection.GeneratedProtocolMessageType('Location', (_message.Message,), {
    'DESCRIPTOR' : _ANALYSISTOKEN_LOCATION,
    '__module__' : 'AnalysisService_pb2'
    # @@protoc_insertion_point(class_scope:com.github.agitolyev.AnalysisToken.Location)
    })
  ,
  'DESCRIPTOR' : _ANALYSISTOKEN,
  '__module__' : 'AnalysisService_pb2'
  # @@protoc_insertion_point(class_scope:com.github.agitolyev.AnalysisToken)
  })
_sym_db.RegisterMessage(AnalysisToken)
_sym_db.RegisterMessage(AnalysisToken.Field)
_sym_db.RegisterMessage(AnalysisToken.Location)


DESCRIPTOR._options = None

_ANALYSISSERVICE = _descriptor.ServiceDescriptor(
  name='AnalysisService',
  full_name='com.github.agitolyev.AnalysisService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=459,
  serialized_end=666,
  methods=[
  _descriptor.MethodDescriptor(
    name='Analyze',
    full_name='com.github.agitolyev.AnalysisService.Analyze',
    index=0,
    containing_service=None,
    input_type=_ANALYSISREQUEST,
    output_type=_ANALYSISREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Anonymize',
    full_name='com.github.agitolyev.AnalysisService.Anonymize',
    index=1,
    containing_service=None,
    input_type=_ANONYMIZATIONREQUEST,
    output_type=_ANONYMIZATIONREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ANALYSISSERVICE)

DESCRIPTOR.services_by_name['AnalysisService'] = _ANALYSISSERVICE

# @@protoc_insertion_point(module_scope)
